---
- include_vars: apache2.yml
- name: Install apache2
  become: yes
  apt:  pkg=apache2 state=latest

- name: apache2 configuration
  become: yes
  template: src=apache2/envvars.j2 dest=/etc/apache2/envvars owner=root group=root mode=644

- name: apache2 servername file
  become: yes
  file: path=/etc/apache2/conf-available/servername.conf state=touch

- name: apache2 servername file config
  become: yes
  lineinfile: dest=/etc/apache2/conf-available/servername.conf state=present line='ServerName localhost'

- name: Enable apache servername #TODO: fix return always changed
  become: yes
  command: a2enconf servername

# apache modules
- name: Install apache modules
  become: yes
  apt:  pkg={{ item.module }} state=latest
  with_items: "{{ apache_install_modules }}"

- name: Disable apache modules
  become: yes
  apache2_module: state=absent name={{ item.module }}
  with_items: "{{ apache_disable_modules }}"

- name: Enable apache modules
  become: yes
  apache2_module: name={{ item.module }}
  with_items: "{{ apache_enable_modules }}"

- name: Disable default site
  become: yes
  file: dest=/etc/apache2/sites-enabled/000-default.conf state=absent

- name: Disable default ssl site
  become: yes
  file: dest=/etc/apache2/sites-enabled/default-ssl.conf state=absent

- name: Change fastcgi owner and group
  file: path=/var/lib/apache2/fastcgi owner={{ user }} group={{ user }}
  become: yes
  notify: restart apache2
